name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        node-version: [16.x, 17.x]
        operating-system: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0-rc.2

      - name: Setup Node.js environment ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm turbo run test
        env:
          CI: true
